[package]
name = "rmusicbot"
version = "0.1.0"
authors = ["Achim Winter"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
serenity = { version = "0.12.0-rc", features = ["cache", "framework", "standard_framework", "voice", "http", "rustls_backend"] }
symphonia = { features = ["mp3"], version = "0.5.2" }
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

[dependencies.songbird]
version = "0.4.0-rc"
features = ["builtin-queue"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread", "signal"]

serde = { version = "1.0", features = ["derive"] }